"""Generate web/src/widths.ts from Kitty's own character width tables.

Run with Kitty's bundled Python so the web view matches the installed Kitty exactly:
    kitty +launch scripts/gen_widths.py
"""

import subprocess
from pathlib import Path

from kitty.fast_data_types import wcswidth

OUT = Path(__file__).resolve().parents[1] / "web/src/widths.ts"
LAST = 0x10FFFF
VS15, VS16 = chr(0xFE0E), chr(0xFE0F)


def width(cp):
    # wcwidth() marks ambiguous, private-use and unassigned characters with negative codes;
    # wcswidth() gives the width Kitty actually lays out.
    return wcswidth(chr(cp))


def valid(cp):
    return not 0xD800 <= cp <= 0xDFFF


def ranges(first, pred):
    out, start = [], None
    for cp in range(first, LAST + 1):
        ok = valid(cp) and pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, LAST))
    return out


def table(name, doc, pairs):
    values = [f"0x{v:x}" for pair in pairs for v in pair]
    lines, line = [], ""
    for value in values:
        if len(line) + len(value) + 2 > 98:
            lines.append(line.rstrip())
            line = ""
        line += value + ", "
    lines.append(line.rstrip())
    body = "\n".join("  " + text for text in lines)
    return f"/** {doc} */\nexport const {name}: readonly number[] = [\n{body}\n];\n"


version = subprocess.run(["kitty", "--version"], capture_output=True, text=True).stdout.split()[1]
parts = [
    f"// Generated by scripts/gen_widths.py from Kitty {version}; do not edit by hand.\n"
    "// Each table is a flat, sorted list of inclusive [first, last] code point pairs.\n",
    table("WIDE", "Two cells wide.", ranges(0x80, lambda cp: width(cp) == 2)),
    table(
        "ZERO",
        "Zero width: combining marks, joiners and selectors.",
        ranges(0x80, lambda cp: width(cp) == 0),
    ),
    table(
        "VS16_WIDE",
        "One-cell characters that become two cells when followed by U+FE0F.",
        ranges(0x20, lambda cp: width(cp) == 1 and wcswidth(chr(cp) + VS16) == 2),
    ),
    table(
        "VS15_NARROW",
        "Two-cell characters that become one cell when followed by U+FE0E.",
        ranges(0x80, lambda cp: width(cp) == 2 and wcswidth(chr(cp) + VS15) == 1),
    ),
]
OUT.write_text("\n".join(parts))
print(f"wrote {OUT}")
